In [23]:
import pandas as pd
df=pd.DataFrame()
import requests
collected=[]
for i in range(1,40):
        cookies = {
            '_t_s': 'seo',
            '_t_sd': 'google',
            '_t_ds': 'f6c0b61690980650-36f6c0b6-0f6c0b6',
            '_t_us': '64CA512A',
            'test': 'naukri.com',
            '_t_us': '64CA512A',
            '_t_s': 'seo',
            '_t_sd': 'google',
            '_t_r': '1030%2F%2F',
            'persona': 'default',
            '_t_ds': 'f6c0b61690980650-36f6c0b6-0f6c0b6',
            'bm_sz': 'C4393DC3ED74478DCC4DDC787F0E34D6~YAAQHW/ZF+NEq7SJAQAAWgxNthT0tbWvCA/tCPr0m/Iw1M6i+R0AmR06MeNdKeEyEIwB9eG1eyuWO6DYVINeshYwWqSSeWffalbzuvStQAm0f4HXg2aQvK1WTndv5zHEt/sh6PlQlPmPKK/HfZN5gNqcKkk3qn+mhlRu7NpowyCJdutSe16iHCmYxS9INv86MMgfZfW9VmXrEjIp4uWKMnEVsX8cf7onZz/k2hwEI9DE7y/Cj7MN4v1rH7w1twsP65CXyIzH3WSc7qGExdjaJTfE8BB/8RoAn3tzfEWafPNe09c=~3228976~3749938',
            '_gcl_au': '1.1.1383103655.1690980644',
            '_gid': 'GA1.2.1728027691.1690980644',
            'ak_bmsc': '8B08AD831036DBDDF3B9155A30C235D3~000000000000000000000000000000~YAAQHW/ZF/5Eq7SJAQAA0w9NthQqfwhZR0r/WEs9zCcKS4S5E4PEd2hUCX6Yy5IMEAKz0yGTewFoE3ClP6BCTJpDdIiLdodYypSfT2I1AJmwalV5OTToxFN+OE9V+4FCplkyMLLcVA1YuRkEDZVCztRDf5v2KA+j4XoD5aYEDlZVYV0oipxJHqjEEkTL29uc/0tTZeLnKuHAUPQRWGv8/k1gqth4AEuWEmPjgz+ciDXki4c5sG00BzWj48u2/3uyw361wvrXrlnb18GehD23ZovuXeXn1P2LZoi2kYqd2H/sKKpbhmgUiHkAWe9H5lNGsTqPhXk3Y7qmpSpbLKPWpjQIEfQ+jChSroDWyo2XZLGyyFZkYKR3XKOSHS7Q2OcDo9H+fGy1RKUs2XuhgyVgAhzpX3PDjHnpy1WlVplICdn6SkES6OUEUHVQf4t6P+9kL/R16VfXwR1KiNh60fUuDO4W+9/EmnG3T8GInnX7cIbF28lWv8iZ+0+RKORas2ePmLo/7ikwUw0Rp/rMoTf+uts=',
            '_abck': 'E0B5A75CD13BDA7F46FEF69CA3D53678~0~YAAQHW/ZFwFFq7SJAQAA0hBNtgqu/UuQLOf8qusg1e+QkExH7A9pveOi5BvqMFZHwP9zubKd2cY2PQf6vlAoPPHOL3Qloc+TQvcXJwDKzMTZYirZn16RsmIh7GgZGFYQPXECz1gvIT45217gxqlG/XcJVkGrrKUmZZV9TwgvETKMh89PaVECx0JFCN+efVyaumIcIaUR1NAQrMyXxbQAkdYn3oWcLXlzxhcStNscE6+1WC99VltHP/JBlz9DtL1x+CRcNleQRtyXa4UYT1wu44AKYg2SBRA+CH0AohiT7H0AgMwtoqZWi1nqu6Y/+plGdJcT307jNbgEERr3vK50bqSDpMCdm+KpMXfOTeoeyofb8Rf6FaZJdULQXgNQA6Dk5oELgB6URcUpfWdoOmkJZ8YFAXgfMHzm~-1~||-1||~-1',
            '_fbp': 'fb.1.1690980647569.651347663',
            '__gads': 'ID=925c354d8281411c:T=1690980656:RT=1690980656:S=ALNI_MZbVQq0VRWnzbCoOOk0mHFDsNSiew',
            '__gpi': 'UID=00000c2650e06bff:T=1690980656:RT=1690980656:S=ALNI_MZQ5-fmpE-DOc4X0aIhTSmmGluR-g',
            '_cc_id': '5aa0fb321d85387498274df32995e5c3',
            'panoramaId_expiry': '1691067057359',
            'cto_bundle': 'B5pqNl9ZZkZvUEhvNGhYRFJBQWJTZEFRTzI5dTQzTHR5S25vUjV6cHpVbFMzJTJCTnZkNmRrTll2QVBJRDVySHIlMkJON3NlWTh3Tkh1RWM2ZXBKc2REVkFIU1N4MVBwdlE5TUFldVZadUszTzlMVVdJYVZycFlpT0w2eVE3RE1IUmtON09VaTQ',
            '_ga': 'GA1.2.1349655740.1690980644',
            '_ga_K2YBNZVRLL': 'GS1.1.1690980644.1.1.1690980857.60.0.0',
            'bm_sv': 'A9304D6C673189C53195534E63F3386D~YAAQN2/ZF6Mxr6eJAQAAJFJQthSxI9bOOXViaNQWpOCuqBWn5XQJVvjlL2bX3fwCN/XCd/tJCOJZjgOsoF4mRJLXkPCsk/8Oow1QZtG2wQ8T32DVAFClvZ3WBA+us6VYHIRYy70Fgsvn825SRkP2awIK461RQ/UgXpGwRbjMEPdlXkbL4odV/DMtB4/2pRwDOB2bFrxIW3l562MhS0smQlzinbuYh8OULJxfbC3p1Mithq2YnrUnzsN+HzfNbKLqeQ==~1',
            'HOWTORT': 'cl=1690981129021&r=https%3A%2F%2Fwww.naukri.com%2Fdata-scientist-jobs-2%3Fk%3Ddata%2520scientist&nu=https%3A%2F%2Fwww.naukri.com%2Fdata-scientist-jobs',
        }

        headers = {
            'authority': 'www.naukri.com',
            'accept': 'application/json',
            'accept-language': 'en-IN,en-GB;q=0.9,en-US;q=0.8,en;q=0.7',
            'appid': '109',
            'cache-control': 'no-cache',
            'clientid': 'd3skt0p',
            'content-type': 'application/json',
            # 'cookie': '_t_s=seo; _t_sd=google; _t_ds=f6c0b61690980650-36f6c0b6-0f6c0b6; _t_us=64CA512A; test=naukri.com; _t_us=64CA512A; _t_s=seo; _t_sd=google; _t_r=1030%2F%2F; persona=default; _t_ds=f6c0b61690980650-36f6c0b6-0f6c0b6; bm_sz=C4393DC3ED74478DCC4DDC787F0E34D6~YAAQHW/ZF+NEq7SJAQAAWgxNthT0tbWvCA/tCPr0m/Iw1M6i+R0AmR06MeNdKeEyEIwB9eG1eyuWO6DYVINeshYwWqSSeWffalbzuvStQAm0f4HXg2aQvK1WTndv5zHEt/sh6PlQlPmPKK/HfZN5gNqcKkk3qn+mhlRu7NpowyCJdutSe16iHCmYxS9INv86MMgfZfW9VmXrEjIp4uWKMnEVsX8cf7onZz/k2hwEI9DE7y/Cj7MN4v1rH7w1twsP65CXyIzH3WSc7qGExdjaJTfE8BB/8RoAn3tzfEWafPNe09c=~3228976~3749938; _gcl_au=1.1.1383103655.1690980644; _gid=GA1.2.1728027691.1690980644; ak_bmsc=8B08AD831036DBDDF3B9155A30C235D3~000000000000000000000000000000~YAAQHW/ZF/5Eq7SJAQAA0w9NthQqfwhZR0r/WEs9zCcKS4S5E4PEd2hUCX6Yy5IMEAKz0yGTewFoE3ClP6BCTJpDdIiLdodYypSfT2I1AJmwalV5OTToxFN+OE9V+4FCplkyMLLcVA1YuRkEDZVCztRDf5v2KA+j4XoD5aYEDlZVYV0oipxJHqjEEkTL29uc/0tTZeLnKuHAUPQRWGv8/k1gqth4AEuWEmPjgz+ciDXki4c5sG00BzWj48u2/3uyw361wvrXrlnb18GehD23ZovuXeXn1P2LZoi2kYqd2H/sKKpbhmgUiHkAWe9H5lNGsTqPhXk3Y7qmpSpbLKPWpjQIEfQ+jChSroDWyo2XZLGyyFZkYKR3XKOSHS7Q2OcDo9H+fGy1RKUs2XuhgyVgAhzpX3PDjHnpy1WlVplICdn6SkES6OUEUHVQf4t6P+9kL/R16VfXwR1KiNh60fUuDO4W+9/EmnG3T8GInnX7cIbF28lWv8iZ+0+RKORas2ePmLo/7ikwUw0Rp/rMoTf+uts=; _abck=E0B5A75CD13BDA7F46FEF69CA3D53678~0~YAAQHW/ZFwFFq7SJAQAA0hBNtgqu/UuQLOf8qusg1e+QkExH7A9pveOi5BvqMFZHwP9zubKd2cY2PQf6vlAoPPHOL3Qloc+TQvcXJwDKzMTZYirZn16RsmIh7GgZGFYQPXECz1gvIT45217gxqlG/XcJVkGrrKUmZZV9TwgvETKMh89PaVECx0JFCN+efVyaumIcIaUR1NAQrMyXxbQAkdYn3oWcLXlzxhcStNscE6+1WC99VltHP/JBlz9DtL1x+CRcNleQRtyXa4UYT1wu44AKYg2SBRA+CH0AohiT7H0AgMwtoqZWi1nqu6Y/+plGdJcT307jNbgEERr3vK50bqSDpMCdm+KpMXfOTeoeyofb8Rf6FaZJdULQXgNQA6Dk5oELgB6URcUpfWdoOmkJZ8YFAXgfMHzm~-1~||-1||~-1; _fbp=fb.1.1690980647569.651347663; __gads=ID=925c354d8281411c:T=1690980656:RT=1690980656:S=ALNI_MZbVQq0VRWnzbCoOOk0mHFDsNSiew; __gpi=UID=00000c2650e06bff:T=1690980656:RT=1690980656:S=ALNI_MZQ5-fmpE-DOc4X0aIhTSmmGluR-g; _cc_id=5aa0fb321d85387498274df32995e5c3; panoramaId_expiry=1691067057359; cto_bundle=B5pqNl9ZZkZvUEhvNGhYRFJBQWJTZEFRTzI5dTQzTHR5S25vUjV6cHpVbFMzJTJCTnZkNmRrTll2QVBJRDVySHIlMkJON3NlWTh3Tkh1RWM2ZXBKc2REVkFIU1N4MVBwdlE5TUFldVZadUszTzlMVVdJYVZycFlpT0w2eVE3RE1IUmtON09VaTQ; _ga=GA1.2.1349655740.1690980644; _ga_K2YBNZVRLL=GS1.1.1690980644.1.1.1690980857.60.0.0; bm_sv=A9304D6C673189C53195534E63F3386D~YAAQN2/ZF6Mxr6eJAQAAJFJQthSxI9bOOXViaNQWpOCuqBWn5XQJVvjlL2bX3fwCN/XCd/tJCOJZjgOsoF4mRJLXkPCsk/8Oow1QZtG2wQ8T32DVAFClvZ3WBA+us6VYHIRYy70Fgsvn825SRkP2awIK461RQ/UgXpGwRbjMEPdlXkbL4odV/DMtB4/2pRwDOB2bFrxIW3l562MhS0smQlzinbuYh8OULJxfbC3p1Mithq2YnrUnzsN+HzfNbKLqeQ==~1; HOWTORT=cl=1690981129021&r=https%3A%2F%2Fwww.naukri.com%2Fdata-scientist-jobs-2%3Fk%3Ddata%2520scientist&nu=https%3A%2F%2Fwww.naukri.com%2Fdata-scientist-jobs',
            'dnt': '1',
            'gid': 'LOCATION,INDUSTRY,EDUCATION,FAREA_ROLE',
            'pragma': 'no-cache',
            'referer': 'https://www.naukri.com/data-scientist-jobs?k=data%20scientist',
            'sec-ch-ua': '"Not/A)Brand";v="99", "Google Chrome";v="115", "Chromium";v="115"',
            'sec-ch-ua-mobile': '?0',
            'sec-ch-ua-platform': '"Windows"',
            'sec-fetch-dest': 'empty',
            'sec-fetch-mode': 'cors',
            'sec-fetch-site': 'same-origin',
            'systemid': '109',
            'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
        }

        params = {
            'noOfResults': '20',
            'urlType': 'search_by_keyword',
            'searchType': 'adv',
            'keyword': 'data scientist',
            'pageNo': f'{i}',
            'sort': 'r',
            'k': 'data scientist',
            'seoKey': 'data-scientist-jobs',
            'src': 'jobsearchDesk',
            'latLong': '',
            'sid': '16909806851055420_1',
        }
        response = requests.get('https://www.naukri.com/jobapi/v3/search', params=params, cookies=cookies, headers=headers)
        data=response.json()
        jobs=data['jobDetails']
        
        for each in jobs:
            collect={
                'job_id':each['jobId'],
                "title":(each['title']),
                "posted":each['footerPlaceholderLabel'],
                'company_name':each['companyName'],
                'skills':each['tagsAndSkills'],
                "exp":each['placeholders'][0]['label'],
                "salary":each['placeholders'][1]['label'],
                "offered_location":each['placeholders'][2]['label'],
                "job_Description":each['jobDescription']
            }
            collected.append(collect)

In [24]:
df=pd.DataFrame.from_dict(collected)

In [27]:
df.head()

,jpb_id,title,posted,company_name,skills,exp,salary,offered_location,job_Description
0,130223902315,Analystics & Modeling Specialist,9 Days Ago,Accenture,"Bfsi,Consulting,Machine learning,Open source,P...",6-8 Yrs,Not disclosed,"Kolkata, Mumbai, Hyderabad/Secunderabad, Pune,...",This role will be a part of Survey Solutions a...
1,290723501787,Data Scientist - Senior Associate,4 Days Ago,PwC,"Cloud computing,deep learning,Automation,data ...",4-6 Yrs,Not disclosed,"Mumbai, Hyderabad/Secunderabad, Bangalore/Beng...","<p> <span> As a Data Scientist, you will be re..."
2,130223902578,Data Science Specialist,21 Days Ago,Accenture,"Product management,Change management,Consultin...",2-4 Yrs,Not disclosed,"Kolkata, Mumbai, Hyderabad/Secunderabad, Pune,...",Must Have Knowledge of statistical techniques ...
3,210723000027,Data Scientist,13 Days Ago,PwC,"Data Science,Python,Tensorflow,Pandas,numpy,Ma...",3-6 Yrs,Not disclosed,"Bangalore/Bengaluru, Mumbai (All Areas)",Experience:5 to 6 Years. Notice period:Immedia...
4,020823500576,Staff Data Scientist,1 Day Ago,Visa Inc,"Data analysis,Linux,Data structures,Windows,Cu...",5-10 Yrs,Not disclosed,Bangalore/Bengaluru,<p> </p><ul> <li> As a Staff Data Scientist in...